# Dataset merge
In this notebook we are going to create the different files used for the models. This means we will generate the files after merging with some extermnal datasets.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

We import the files to be merged

In [20]:
data = pd.read_csv('../Data/TFM_Hdataset_clean.csv', index_col=0)
raw_boots = pd.read_csv("../Data/GT_boots.csv",skiprows=1,infer_datetime_format=True)
raw_sandals = pd.read_csv("../Data/GT_sandals.csv",skiprows=1,infer_datetime_format=True)
raw_goretex = pd.read_csv("../Data/GT_goretex.csv",skiprows=1,infer_datetime_format=True)
raw_slippers = pd.read_csv("../Data/GT_slippers.csv",skiprows=1,infer_datetime_format=True)
raw_formalshoes = pd.read_csv("../Data/GT_formalshoes.csv",skiprows=1,infer_datetime_format=True)

In [24]:
raw_boots['style']='Boots'
raw_sandals['style']='Sandals'
raw_goretex['style']='Goretex'
raw_slippers['style']='Slippers'

raw_boots=raw_boots.rename(columns={'Setmana': 'Date','boots: (Regne Unit)':'boots'})
raw_sandals=raw_sandals.rename(columns={'Setmana': 'Date','sandals: (Regne Unit)':'sandals'})
raw_goretex=raw_goretex.rename(columns={'Setmana': 'Date','Goretex: (Regne Unit)':'goretex'})
raw_slippers=raw_slippers.rename(columns={'Setmana': 'Date','slippers: (Regne Unit)':'slippers'})

raw_boots['Date'] =  pd.to_datetime(raw_boots['Date'])
raw_sandals['Date'] =  pd.to_datetime(raw_sandals['Date'])
raw_goretex['Date'] =  pd.to_datetime(raw_goretex['Date'])
raw_slippers['Date'] =  pd.to_datetime(raw_slippers['Date'])

data['Date'] =  pd.to_datetime(data['Date'])

In [17]:
raw_boots

          Date  boots  style
0   2017-01-01     57  Boots
1   2017-01-08     54  Boots
2   2017-01-15     55  Boots
3   2017-01-22     45  Boots
4   2017-01-29     43  Boots
..         ...    ...    ...
256 2021-11-28     85  Boots
257 2021-12-05     83  Boots
258 2021-12-12     82  Boots
259 2021-12-19     82  Boots
260 2021-12-26     82  Boots

[261 rows x 3 columns]

In [22]:
data['Date']

0         2017-01-08
1         2017-01-08
2         2017-01-08
3         2017-01-08
4         2017-01-08
             ...
324424    2021-12-19
324425    2021-12-19
324426    2021-12-19
324427    2021-12-19
324428    2021-12-19
Name: Date, Length: 324429, dtype: object

In [25]:
data_merged = data.merge(raw_boots, how='left', on=['Date','style'])
data_merged = data_merged.merge(raw_sandals, how='left', on=['Date','style'])
data_merged = data_merged.merge(raw_slippers, how='left', on=['Date','style'])
data_merged = data_merged.merge(raw_goretex, how='left', on=['Date','style'])

#fill the nan
data_merged['boots'] = data_merged['boots'].fillna(0)
data_merged['sandals'] = data_merged['sandals'].fillna(0)
data_merged['slippers'] = data_merged['slippers'].fillna(0)
data_merged['goretex'] = data_merged['goretex'].fillna(0)
data_merged

,Description,Seasonality,Year,Week,Channel,WSSI Category,LIMITED EDITION STYLES,Originals,Source,sales,...,Markdown,Cost,month,Channel2,CategoryCluster,ProductCluster,boots,sandals,slippers,goretex
0,Astrid,OLD,2017,1,DE Direct,Womens Active Shoes,0.0,0.0,NONE,1.0,...,11.851731,12.768232,1,US,Cluster 6,Cluster 2,0.0,0.0,0.0,0.0
1,Charmaine,SS,2017,1,DE Direct,Womens Formal Shoes,0.0,0.0,NONE,1.0,...,0.169733,14.124805,1,US,Cluster 0,Cluster 2,0.0,0.0,0.0,0.0
2,Chile,SS,2017,1,DE Direct,Womens Casual Shoes,0.0,0.0,NONE,1.0,...,0.169733,11.576091,1,US,Cluster 3,Cluster 7,0.0,0.0,0.0,0.0
3,Devotion,AW,2017,1,DE Direct,Womens Slippers,0.0,0.0,NONE,2.0,...,8.231530,8.575187,1,US,Cluster 0,Cluster 2,0.0,0.0,13.0,0.0
4,Donna,CONT,2017,1,DE Direct,Womens Formal Shoes,0.0,0.0,NONE,1.0,...,0.209836,15.867796,1,US,Cluster 0,Cluster 7,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324424,Waltham,AW,2021,50,Wholesale,Womens Casual Boots,0.0,0.0,MANUFACTURED,20.0,...,35.000000,22.968000,12,UK,Cluster 4,Cluster 6,82.0,0.0,0.0,0.0
324425,Whisper,AW,2021,50,Wholesale,Womens Casual Boots,0.0,0.0,MANUFACTURED,74.0,...,25.246982,19.778649,12,UK,Cluster 4,Cluster 4,82.0,0.0,0.0,0.0
324426,Whisper,CONT,2021,50,Wholesale,Womens Casual Boots,0.0,0.0,MANUFACTURED,83.0,...,15.790441,19.088072,12,UK,Cluster 4,Cluster 4,82.0,0.0,0.0,0.0
324427,Wrap,AW,2021,50,Wholesale,Womens Slippers,0.0,0.0,MANUFACTURED,28.0,...,19.996666,14.690000,12,UK,Cluster 0,Cluster 2,0.0,0.0,51.0,0.0
324428,Wrap,CONT,2021,50,Wholesale,Womens Slippers,0.0,0.0,MANUFACTURED,34.0,...,20.824902,14.690000,12,UK,Cluster 0,Cluster 2,0.0,0.0,51.0,0.0

In [27]:
data.columns

Index(['Description', 'Seasonality', 'Year', 'Week', 'Channel',
       'WSSI Category', 'LIMITED EDITION STYLES', 'Originals', 'Source',
       'sales', 'gender', 'style', 'prev_sales', 'prev_sales2', 'prev_sales3',
       'prev_sales4', 'prev_mean_price', 'Date', 'Price', 'Discount', 'Margin',
       'RRP', 'Markdown', 'Cost', 'month', 'Channel2', 'CategoryCluster',
       'ProductCluster'],
      dtype='object')

In [26]:
data.to_csv('../Data/TFM_Hdataset_Gtrends.csv')